.idea/.gitignore, .idea/inspectionProfiles/profiles_settings.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, .idea/프로그래머스.iml, 보경/프로그래머스/Level1/문자열 내 p와 y의 개수/문자열 내 p와 y의 개수.py
https://school.programmers.co.kr/learn/courses/30/lessons/12916?language=python3
1. s.lower: 문자열 모두 소문자로 바꾸기
2. .count: p와 y의 개수가 같으면 true, 아니면 false 리턴
O(n)
함수 사용법 알아두기!
공부
=> level1_1 문자열 내 p와 y의 개수

주영/프로그래머스/2/12941. 최솟값 만들기/최솟값 만들기.py
=> test_issue

보경/프로그래머스/1/12906. 같은 숫자는 싫어/같은 숫자는 싫어.py, 보경/프로그래머스/1/12940. 최대공약수와 최소공배수/최대공약수와 최소공배수.py, 보경/프로그래머스/1/12969. 직사각형 별찍기/직사각형 별찍기.py, 보경/프로그래머스/1/12982. 예산/예산.py
#39 
12906, 12940, 12969, 12982
12940(최대공약수와 최소공배수)
쌩구현 했지만 math.gcd(a,b), math.lcm(a, b) 함수 사용하면 더 짧게 구현할 수 있을 것 같다
https://blog.naver.com/heavencoding/223171171641
=> [1주차] 보경_4일차

주영/프로그래머스/1/140108. 문자열 나누기/README.md, 주영/프로그래머스/1/140108. 문자열 나누기/문자열 나누기.py, 주영/프로그래머스/1/155652. 둘만의 암호/README.md, 주영/프로그래머스/1/155652. 둘만의 암호/둘만의 암호.py, 주영/프로그래머스/1/77484. 로또의 최고 순위와 최저 순위/README.md, 주영/프로그래머스/1/77484. 로또의 최고 순위와 최저 순위/로또의 최고 순위와 최저 순위.py
#92 
로또의 최고순위와 최저순위
문자열 나누기
둘만의 암호
둘만의 암호
프로그래머스 질문하기
오답정리한 본인 블로그
https://ju00stu.tistory.com/151
=> [3주차] 주영_5일차

주영/프로그래머스/1/250121. ［PCCE 기출문제］ 10번 ／ 데이터 분석/README.md, 주영/프로그래머스/1/250121. ［PCCE 기출문제］ 10번 ／ 데이터 분석/［PCCE 기출문제］ 10번 ／ 데이터 분석.py, 주영/프로그래머스/1/64061. 크레인 인형뽑기 게임/README.md, 주영/프로그래머스/1/64061. 크레인 인형뽑기 게임/크레인 인형뽑기 게임.py, 주영/프로그래머스/1/67256. ［카카오 인턴］ 키패드 누르기/README.md, 주영/프로그래머스/1/67256. ［카카오 인턴］ 키패드 누르기/［카카오 인턴］ 키패드 누르기.py
#110 
크레인 인형뽑기 게임
10번 / 데이터 분석
키패드 누르기
=> [4주차] 주영_2일차

주영/프로그래머스/1/118666. 성격 유형 검사하기/README.md, 주영/프로그래머스/1/118666. 성격 유형 검사하기/성격 유형 검사하기.py, 주영/프로그래머스/1/161990. 바탕화면 정리/README.md, 주영/프로그래머스/1/161990. 바탕화면 정리/바탕화면 정리.py, 주영/프로그래머스/1/72410. 신규 아이디 추천/README.md, 주영/프로그래머스/1/72410. 신규 아이디 추천/신규 아이디 추천.py
#119 
성격 유형 검사하기
신규 아이디 추천
바탕화면 정리
=> [4주차] 주영_3일차

주영/백준/Gold/2573. 빙산/README.md, 주영/백준/Gold/2573. 빙산/빙산.py
#123 
2573
2573
블로그 참조
본인 오답노트 블로그
https://ju00stu.tistory.com/154
=> [4주차] 주영_5일차

주영/프로그래머스/2/17680. ［1차］ 캐시/README.md, 주영/프로그래머스/2/17680. ［1차］ 캐시/［1차］ 캐시.py
=> [7주차] 주영_1일차

주영/프로그래머스/1/12982. 예산/예산.java, 주영/프로그래머스/1/17681. ［1차］ 비밀지도/［1차］ 비밀지도.java, 주영/프로그래머스/1/68644. 두 개 뽑아서 더하기/두 개 뽑아서 더하기.java
#153 
[1차] 비밀지도
두 개 뽑아서 더하기
예산
=> [8주차] 주영_1일차

주영/프로그래머스/1/12930. 이상한 문자 만들기/이상한 문자 만들기.java, 주영/프로그래머스/1/147355. 크기가 작은 부분문자열/크기가 작은 부분문자열.java, 주영/프로그래머스/1/77884. 약수의 개수와 덧셈/약수의 개수와 덧셈.java
#154 
크기가 작은 부분 문자열
약수의 개수와 덧셈
이상한 문자 만들기
=> [8주차] 주영_2일차

주영/프로그래머스/1/138477. 명예의 전당 （1）/명예의 전당 （1）.java, 주영/프로그래머스/1/142086. 가장 가까운 같은 글자/최소직사각형.java, 주영/프로그래머스/1/86491. 최소직사각형/최소직사각형.java
#157 
명예의 전당(1)
최소직사각형
가장 가까운 같은 글자
=> [8주차] 주영_3일차

주영/프로그래머스/2/42883. 큰 수 만들기/README.md, 주영/프로그래머스/2/42883. 큰 수 만들기/큰 수 만들기.java
=> [8주차] 주영_4일차

주영/프로그래머스/1/12943. 콜라츠 추측/콜라츠 추측.java, 주영/프로그래머스/1/12947. 하샤드 수/하샤드 수.java, 주영/프로그래머스/1/134240. 푸드 파이트 대회/푸드 파이트 대회.java
=> [9주차] 주영_1일차

재연/Programmers/Level1/118666_성격 유형 검사하기.py, 재연/Programmers/Level1/12906_같은 숫자는 싫어.py, 재연/Programmers/Level1/150370_ 개인정보 수집 유효기간.py, 재연/Programmers/Level1/92334_신고 결과 받기.py, 재연/Programmers/Level2/12909_올바른 괄호.py, 재연/Programmers/Level2/42583_다리를 지나는 트럭.py, 재연/Programmers/Level2/42584_주식 가격.py, 재연/Programmers/Level2/42586_기능 개발.py, 재연/Programmers/Level2/42587_프로세스.py
#194 
92334_신고 결과 받기
150370_개인정보 수집 유효기간
258712_가장 많이 받은 선물
12909_올바른 괄호
42583_다리를 지나는 트럭
42584_주식 가격
42586_기능 개발
42587_프로세스
258712_가장 많이 받은 선물
어느정도 로직은 구상했지만 구현으로 옮기는게 어려웠음
=> Jjerry week2

규진/프로그래머스/week2/같은_숫자는_싫어.cpp, 규진/프로그래머스/week2/기능개발.cpp, 규진/프로그래머스/week2/다리를_지나는_트럭.cpp, 규진/프로그래머스/week2/올바른_괄호.cpp, 규진/프로그래머스/week2/프로세스.cpp
=> [2주차] 규진_2일차

재연/Baekjoon/1697_숨바꼭질.py, 재연/Baekjoon/2178_미로 탐색.py, 재연/Baekjoon/4179_불!.py, 재연/Baekjoon/7576_토마토.py, 재연/Programmers/Level1/258712_가장 많이 받은 선물.py, 재연/Programmers/Level2/42587_프로세스.py
#196 
2178_미로 탐색
7576_토마토
4179_불!
1697_숨바꼭질
=> Jjerry week3

재연/Baekjoon/1012_유기농 배추.py, 재연/Baekjoon/13913_ 숨바꼭질 4.py, 재연/Baekjoon/9466_텀 프로젝트.py
=> Add: week4

규진/백준/week4/숨바꼭질_4.cpp, 규진/백준/week4/유기농_배추.cpp, 규진/백준/week4/텀_프로젝트.cpp
=> Kjchoi week6

재연/Baekjoon/1182_부분수열의 합.py, 재연/Baekjoon/11967_불 켜기.py, 재연/Baekjoon/15649_N과M(1).py, 재연/Baekjoon/15650_N과M(2).py, 재연/Baekjoon/15651_N과M(3).py, 재연/Baekjoon/15652_N과M(4).py, 재연/Baekjoon/15653_N과M(5).py, 재연/Baekjoon/15654_N과M(6).py, 재연/Baekjoon/15655_N과M(7).py, 재연/Baekjoon/15656_N과M(8).py, 재연/Baekjoon/15657_N과M(9).py, 재연/Baekjoon/15658_N과M(10).py, 재연/Baekjoon/15659_N과M(11).py, 재연/Baekjoon/15660_N과M(12).py, 재연/Baekjoon/2573_빙산.py, 재연/Baekjoon/5014_스타트링크.py, 재연/Baekjoon/6603_로또.py, 재연/Baekjoon/9663_N-Queen.py
#214 
15649~15660
9663
6603
1182
n-queen 왜 python으로는 시간초과 해결 못하는지
pypy3으로 제출해서 해결
https://seongonion.tistory.com/103
=> Jjerry week7

재연/Baekjoon/11967_불 켜기.py, 재연/Baekjoon/2573_빙산.py, 재연/Baekjoon/5014_스타트링크.py
#209 
9466번, 11967번
불 켜기
ai 활용
=> Jjerry week6

재연/Baekjoon/14712_넴모넴모.py, 재연/Baekjoon/16987_계란으로 계란치기.py, 재연/Baekjoon/1759_암호 만들기.py, 재연/Baekjoon/1799_비숍.py, 재연/Baekjoon/18809_Gaaaaaaaaaarden.py, 재연/Baekjoon/1941_소문난 칠공주.py, 재연/Baekjoon/2580_스도쿠.py, 재연/Baekjoon/6443_애너그램.py
=> Jjerry week9

재연/Baekjoon/11054_가장 긴 바이토닉 부분 수열.py, 재연/Baekjoon/12865_평범한 배낭.py, 재연/Baekjoon/2565_전깃줄.py
=> [11 주차] 민재연

규진/백준/week11/LCS_2.cpp, 규진/백준/week11/가장_긴_바이토닉_부분_수열.cpp, 규진/백준/week11/전깃줄.cpp, 규진/백준/week11/진우의_달_여행.cpp, 규진/백준/week11/평범한_배낭.cpp, 규진/백준/week12/과자_나눠주기.cpp, 규진/백준/week12/기타_레슨.cpp, 규진/백준/week12/나무_자르기.cpp, 규진/백준/week12/숫자_카드_2.cpp, 규진/백준/week12/숫자_카드_다른풀이.cpp
=> Kjchoi week12
